name: My Workflow
on: [push]
jobs:
  my_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out our code
        uses: actions/checkout@master
      - name: Install Deps
        run: sudo apt-get update && export DEBIAN_FRONTEND=noninteractive && sudo apt-get -y install --no-install-recommends sed make binutils build-essential gcc g++ bash patch gzip bzip2 perl tar cpio unzip rsync file bc wget libncurses-dev
      - name: Run Build
        run: make
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: output/images
